db_ip: 127.0.0.1
db_port: 3306
db_database: admin-db
db_username: root
db_password: 123456
spring:
  profiles:
    active: default,dev
  application:
    name: example

logging:
  file:
    path: ./logs
  level:
    io.admin: info

sys:
  captcha: true
